name:           SMV-Haskell
synopsis:       A symbolic model checker written in Haskell
author:         Javier Diego-Fernández @ UNAM Mexico City C.U.
maintainer:     Javier Diego-Fernández <javier.d.fernandez7@gmail.com>
category:       Data


description:    Simple symbolic model checker based on NuSMV written in Haskell, it uses HasCacBDD binding
                to implement the BDD functionality.

extra-source-files:
  - stack.yaml

github: javierdiegof/SMV-Haskell

library:
  exposed-modules:
    - ModelCheck
    - DataTypes
    - Preprocess
    - LanguageDef
    - SMVParser

  dependencies:
    - base >=4.8 && < 5
    - process >= 1.1
    - containers
    - parsec
    - criterion
    - HasCacBDD
    - directory

  source-dirs:
    - src/SMV

  ghc-options:
    - -Wall
  

tests:
  stack-test:
    source-dirs: test
    main: Test1.hs

    dependencies:
      - base >=4.8 && < 5
      - hspec
      - QuickCheck
      - exceptions
      - SMV-Haskell
      - directory
      - HasCacBDD

    ghc-options:
      - -Weverything
      - -threaded

executables:
  test-exe:
    main:         TestEx.hs
    source-dirs:  app
    ghc-options: 
      - -O2
    dependencies:
      - SMV-Haskell
      - base >=4.8 && < 5
  counter-exe:
    main:           Counter.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
  fair-exe:
    main:           Fair.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
  interleave-exe:
    main:           Interleave.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
  shift-exe:
    main:           Shift.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD

# executables:
#   counter3-exe:
#     main:           Counter.hs
#     source-dirs:    app
#     ghc-options:
#     - -O2
#     - -auto-all
#     - -caf-all
#     - -fforce-recomp
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
#     - directory

# executables:
#   counter3-exe:
#     main:           Counter3.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
#   counter4-exe:
#     main:           Counter4.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5

#   counter5-exe:
#     main:           Counter5.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5

#   counter6-exe:
#     main:           Counter6.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5

#   counter7-exe:
#     main:           Counter7.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5

#   counter8-exe:
#     main:           Counter8.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
  
#   counter9-exe:
#     main:           Counter9.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
  
#   counter10-exe:
#     main:           Counter10.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
  
#   counter11-exe:
#     main:           Counter11.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
  
#   counter12-exe:
#     main:           Counter12.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
  
#   counter13-exe:
#     main:           Counter13.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
  
#   counter14-exe:
#     main:           Counter14.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
    
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5

#   counter15-exe:
#     main:           Counter10.hs
#     source-dirs:    app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SMV-Haskell
#     - base >=4.8 && < 5
    
  # fair3-exe:
  #   main:           Fair3.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  # fair4-exe:
  #   main:           Fair4.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair5-exe:
  #   main:           Fair5.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair6-exe:
  #   main:           Fair6.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair7-exe:
  #   main:           Fair7.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  
  # fair8-exe:
  #   main:           Fair8.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair9-exe:
  #   main:           Fair9.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair10-exe:
  #   main:           Fair10.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  
  # fair11-exe:
  #   main:           Fair11.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair12-exe:
  #   main:           Fair12.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair13-exe:
  #   main:           Fair13.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  
  # fair14-exe:
  #   main:           Fair14.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair15-exe:
  #   main:           Fair15.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair16-exe:
  #   main:           Fair16.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # fair17-exe:
  #   main:           Fair17.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift3-exe:
  #   main:           Shift3.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  # shift4-exe:
  #   main:           Shift4.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift5-exe:
  #   main:           Shift5.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift6-exe:
  #   main:           Shift6.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift7-exe:
  #   main:           Shift7.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  
  # shift8-exe:
  #   main:           Shift8.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift9-exe:
  #   main:           Shift9.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift10-exe:
  #   main:           Shift10.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  
  # shift11-exe:
  #   main:           Shift11.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift12-exe:
  #   main:           Shift12.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift13-exe:
  #   main:           Shift13.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5
  
  # shift14-exe:
  #   main:           Shift14.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift15-exe:
  #   main:           Shift15.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift16-exe:
  #   main:           Shift16.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

  # shift17-exe:
  #   main:           Shift17.hs
  #   source-dirs:    app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - SMV-Haskell
  #   - base >=4.8 && < 5

