name:           SMV-Haskell
version:        1.0 # First major release!
synopsis:       A symbolic model checker written in Haskell
author:         Javier Diego-Fernández @ UNAM Mexico City C.U.
maintainer:     Javier Diego-Fernández <javier.d.fernandez7@gmail.com>
category:       Data


description:    Simple symbolic model checker based on NuSMV written in Haskell, it uses HasCacBDD binding
                to implement the BDD functionality.

extra-source-files:
  - stack.yaml

github: javierdiegof/SMV-Haskell

library:
  exposed-modules:
    - ModelCheck
    - DataTypes
    - Preprocess
    - LanguageDef
    - SMVParser

  dependencies:
    - base >=4.8 && < 5
    - process >= 1.1
    - containers
    - parsec
    - criterion
    - HasCacBDD 
    - directory

  source-dirs:
    - src/SMV

  ghc-options:
    - -Wall
  

tests:
  stack-test:
    source-dirs: test
    main: Test.hs

    dependencies:
      - base >=4.8 && < 5
      - hspec
      - QuickCheck
      - exceptions
      - SMV-Haskell
      - directory

    ghc-options:
      - -Weverything
      - -threaded