name:           SMV-Haskell
synopsis:       A symbolic model checker written in Haskell
author:         Javier Diego-Fernández @ UNAM Mexico City C.U.
maintainer:     Javier Diego-Fernández <javier.d.fernandez7@gmail.com>
category:       Data


description:    Simple symbolic model checker based on NuSMV written in Haskell, it uses HasCacBDD binding
                to implement the BDD functionality.

extra-source-files:
  - stack.yaml

github: javierdiegof/SMV-Haskell

library:
  exposed-modules:
    - SemanticCheck
    - DataTypes
    - DataTypesOps
    - LanguageDef
    - SMVParser

  dependencies:
    - base >=4.8 && < 5
    - process >= 1.1
    - containers
    - parsec
    - criterion
    - HasCacBDD

  source-dirs:
    - src/SMV

  ghc-options:
    - -Wall

executables:
  counter-exe:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD

tests:
  stack-test:
    source-dirs: test
    main: Test1.hs

    dependencies:
      - base >=4.8 && < 5
      - hspec
      - QuickCheck
      - exceptions
      - SMV-Haskell
      - directory
      - HasCacBDD

    ghc-options:
      - -Weverything
      - -threaded
