name:           SMV-Haskell
synopsis:       A symbolic model checker written in Haskell
author:         Javier Diego-Fernández @ UNAM Mexico City C.U.
maintainer:     Javier Diego-Fernández <javier.d.fernandez7@gmail.com>
category:       Data


description:    Simple symbolic model checker based on NuSMV written in Haskell, it uses HasCacBDD binding
                to implement the BDD functionality.

extra-source-files:
  - stack.yaml

github: javierdiegof/SMV-Haskell


library:
  exposed-modules:
    - ModelCheck
    - DataTypes
    - Preprocess
    - LanguageDef
    - SMVParser

  dependencies:
    - base >=4.8 && < 5
    - process >= 1.1
    - containers
    - parsec
    - criterion
    - HasCacBDD
    - directory

  source-dirs:
    - src/SMV

  ghc-options:
    - -Wall
  
  

tests:
  stack-test:
    source-dirs: test
    main: Test1.hs

    dependencies:
      - base >=4.8 && < 5
      - hspec
      - QuickCheck
      - exceptions
      - SMV-Haskell
      - directory
      - HasCacBDD

    ghc-options:
      - -Weverything
      - -threaded

executables:
  test-exe1:
    main:         TestEx1.hs
    source-dirs:  app
    ghc-options: 
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SMV-Haskell
      - base >=4.8 && < 5
      - HasCacBDD
      - directory
      - HasCacBDD
  test-exe2:
    main:         TestEx2.hs
    source-dirs:  app
    ghc-options: 
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SMV-Haskell
      - base >=4.8 && < 5
      - HasCacBDD
      - directory
      - HasCacBDD
  counter-exe:
    main:           Counter.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
  fair-exe:
    main:           Fair.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
  interleave-exe:
    main:           Interleave.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
  shift-exe:
    main:           Shift.hs
    source-dirs:    app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SMV-Haskell
    - base >=4.8 && < 5
    - HasCacBDD
    - directory
    - HasCacBDD
